/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

/**
 * Returns a greeting.
 */
public class App {
    public String getGreeting() {
        return "Hello again, World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
